services:
  - type: web
    name: stock-sense-api
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ALPHA_VANTAGE_API_KEY
        sync: false

